name       : haskell-vector-algorithms
version    : 0.7.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/vector-algorithms-0.7.0.1/vector-algorithms-0.7.0.1.tar.gz : ed460a41ca068f568bc2027579ab14185fbb72c7ac469b5179ae5f8a52719070
license    : BSD-3-Clause
component  : programming.haskell
summary    : Efficient algorithms for vector arrays 
description: |
    Efficient algorithms for vector arrays 
builddeps  :
    - haskell-cabal-install
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
