name       : haskell-vector-algorithms
version    : 0.8.0.3
release    : 3
source     :
    - https://hackage.haskell.org/package/vector-algorithms-0.8.0.3/vector-algorithms-0.8.0.3.tar.gz : 1ac41f014663fd318b34a76b80e6d8f32f1629ef4996ae7304f31597a0d07387
license    : BSD-3-Clause
component  : programming.haskell
summary    : Efficient algorithms for vector arrays
description: |
    Efficient algorithms for vector arrays
builddeps  :
    - haskell-cabal-install
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
